package io.github.yulily.ab.controller;

import io.github.yulily.ab.model.Expense;
import io.github.yulily.ab.model.repository.ExpenseRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/expense") // This means URL's start with /demo (after Application path)
public class ExpenseController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ExpenseRepository expenseRepository;

    @GetMapping(path="/show")
    public @ResponseBody Iterable<Expense> get() {
        return expenseRepository.findAll();
    }

    @GetMapping(path="/year")
    public @ResponseBody Iterable<Expense> getByYear() {
        return expenseRepository.findAll();
    }

    @PostMapping(path="/update") // Map ONLY POST Requests
    public @ResponseBody String update(
            @RequestParam String title
    ) {
        Expense n = new Expense();
        n.setTitle(title);
        expenseRepository.save(n);
        return "Updated";
    }

    @PostMapping(path="/create") // Map ONLY POST Requests
    public @ResponseBody String create(
            @RequestParam String title
    ) {
        Expense n = new Expense();
        n.setTitle(title);
        expenseRepository.save(n);
        return "Saved";
    }
}